[package]
name = "availability-tracker"
description = "Track availability of address over time"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "track-availability"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
crossterm = "0.29.0"
humantime = "2.3.0"
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
time = { version = "0.3.47", features = ["formatting", "local-offset", "macros"] }
